# Generated by Django 4.2.1 on 2023-05-24 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=128, verbose_name="Полное название"),
                ),
                (
                    "short_name",
                    models.CharField(max_length=128, verbose_name="Краткое название"),
                ),
                ("foundation_date", models.DateField(verbose_name="Дата Создания")),
            ],
            options={
                "verbose_name": "Университет",
                "verbose_name_plural": "Университеты",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fitst_name", models.CharField(max_length=64, verbose_name="Имя")),
                (
                    "second_name",
                    models.CharField(max_length=64, verbose_name="Фамилия"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(null=True, verbose_name="Дата Рождения"),
                ),
                ("admission_date", models.DateField(verbose_name="Дата поступления")),
                (
                    "university",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mainapp.university",
                        verbose_name="Университет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "ordering": ["second_name"],
            },
        ),
    ]
