# Generated by Django 4.2.1 on 2023-05-24 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["second_name", "fitst_name"],
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
            },
        ),
        migrations.AlterField(
            model_name="student",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mainapp.university",
                verbose_name="Университет",
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="full_name",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Полное название"
            ),
        ),
    ]
